# Generated by Django 2.0.6 on 2018-06-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180610_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='category',
        ),
        migrations.AddField(
            model_name='description',
            name='category',
            field=models.ForeignKey(default='', on_delete=True, to='app.Category', verbose_name='カテゴリ'),
        ),
    ]
