# Generated by Django 2.0.6 on 2018-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180610_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='category',
            field=models.ForeignKey(on_delete=True, to='app.Category', verbose_name='カテゴリ'),
        ),
    ]
